"""add date_added to favorite_prompt

Revision ID: 1e96b22a1867
Revises: 8529cf42bb11
Create Date: 2023-05-30 18:34:22.316715

"""

from alembic import op
import sqlalchemy as sa

import datetime
from zoneinfo import ZoneInfo


# revision identifiers, used by Alembic.
revision = '1e96b22a1867'
down_revision = '8529cf42bb11'
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.add_column('favorite_prompt', sa.Column('date_added', sa.TIMESTAMP(), nullable=False, server_default=str(datetime.datetime.now(ZoneInfo('Europe/Moscow')))))
    op.alter_column('favorite_prompt', 'date_added', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_prompt', 'date_added')
    # ### end Alembic commands ###
