"""add workspace title

Revision ID: 4ade20b0f214
Revises: 1c0d1f79a3b6
Create Date: 2023-06-17 14:44:46.370775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ade20b0f214'
down_revision = '1c0d1f79a3b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('workspace', sa.Column('title', sa.String(), nullable=False, unique=True, server_default='first'))
    op.alter_column('workspace', 'title', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'title')
    # ### end Alembic commands ###
