"""add username and company

Revision ID: 864d43c0baca
Revises: 8b72a956fb58
Create Date: 2023-05-27 18:50:55.858213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864d43c0baca'
down_revision = '8b72a956fb58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_interaction', sa.Column('username', sa.String(), nullable=False))
    op.add_column('gpt_interaction', sa.Column('company', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpt_interaction', 'company')
    op.drop_column('gpt_interaction', 'username')
    # ### end Alembic commands ###
