"""add favorite prompts

Revision ID: 8b72a956fb58
Revises: abd6146423c1
Create Date: 2023-05-25 18:44:06.332918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b72a956fb58'
down_revision = 'abd6146423c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_prompt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_prompt_blank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('favorite_prompt_id', sa.UUID(), nullable=True),
    sa.Column('text_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_prompt_id'], ['favorite_prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match_prompt_blank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_prompt_blank',
    sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_blank_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name='match_prompt_blank_match_id_fkey'),
    sa.ForeignKeyConstraint(['prompt_blank_id'], ['prompt_blank.id'], name='match_prompt_blank_prompt_blank_id_fkey'),
    sa.PrimaryKeyConstraint('match_id', 'prompt_blank_id', name='match_prompt_blank_pkey')
    )
    op.drop_table('favorite_prompt_blank')
    op.drop_table('favorite_prompt')
    # ### end Alembic commands ###
