"""add color to match

Revision ID: abd6146423c1
Revises: f25d736a03eb
Create Date: 2023-05-25 14:34:24.935446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd6146423c1'
down_revision = 'f25d736a03eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'color')
    # ### end Alembic commands ###
