"""change question to match (question and answer)

Revision ID: f25d736a03eb
Revises: 
Create Date: 2023-05-24 16:25:13.667306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25d736a03eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_interaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gpt_answer', sa.String(), nullable=False),
    sa.Column('time_happened', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_blank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filled_prompt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_data', sa.String(), nullable=False),
    sa.Column('gpt_interaction_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['gpt_interaction_id'], ['gpt_interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_prompt_blank',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('prompt_blank_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['prompt_blank_id'], ['prompt_blank.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'prompt_blank_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_prompt_blank')
    op.drop_table('filled_prompt')
    op.drop_table('prompt_blank')
    op.drop_table('match')
    op.drop_table('gpt_interaction')
    # ### end Alembic commands ###
